# Numpy Tricks to keep in mind while coding
This jupyter notebook is intended to keep track of list of small tricks while coding numpy arrays
 - Vectors are denoted by small letters, say a, b
 - Matrices are denoted by capital letters say A, B 

In [1]:
# Import the required libraries
import numpy as np

### Create Numpy arrays of desired shape

In [14]:
a = np.array([1,2,3,4,5])
print('Numpy Array a =', a)
print('Shape of numpy array a is ', a.shape)
print('Number of elements in array a =', a.shape[0])

Numpy Array a = [1 2 3 4 5]
Shape of numpy array a is  (5,)
Number of elements in array a = 5


### Create Numpy arrays of ones and zeros

In [5]:
a = np.ones(5)
b = np.zeros(5)
print('a = ', a)
print('b = ', b)
print('Shape of numpy array a is ', a.shape)
print('Shape of numpy array b is ', b.shape)

a =  [1. 1. 1. 1. 1.]
b =  [0. 0. 0. 0. 0.]
Shape of numpy array a is  (5,)
Shape of numpy array b is  (5,)


### Create row vectors & column vectors
It is upto us to reshape the above numpy array as either row vector or a column vector depending upon our needs. Let us now see how to reshape them into row vector and a column vector respectively.

In [31]:
# Create the original numpy array
a = np.ones(5)
print('a = ', a)
print('Shape of original numpy array a is ', a.shape)

# Create a column vector out of a
b = np.ones(5).reshape(-1, 1)  # or equivalently b = a.reshape(-1, 1) will do the same
print('b = ', b)
print('Shape of numpy array b is ', b.shape)
# Transpose it to see the shape and array value
c = b.T
print('c = b.T =', c)
print('Shape of numpy array c is ', c.shape)

# Above c is also a row vector - however, we can directly create a row vector as follows
c = np.array([1,2,3,4,5]).reshape(1,-1)
print('c =', c)
print('Shape of numpy array c is ', c.shape)

a =  [1. 1. 1. 1. 1.]
Shape of original numpy array a is  (5,)
b =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Shape of numpy array b is  (5, 1)
c = b.T = [[1. 1. 1. 1. 1.]]
Shape of numpy array c is  (1, 5)
c = [[1 2 3 4 5]]
Shape of numpy array c is  (1, 5)


### Inner and outer products of vectors
 - Inner product of vectors $a, b$ is denoted by $<a,b> = a^{\top}b$ and it is a scalar
 - Outer product of vectors $a, b \in \mathbb{R}^{n}$ is denoted by $a \otimes b = a b^{\top}$ and it is a matrix of size $n \times n$
 - Also $<a,b> = \sum (trace(a \otimes b))$

In [29]:
# Create a column vector
a = np.array([1,2,3,4,5]).reshape(-1,1)
print('a = ', a)
print('Shape of numpy array a is ', a.shape)

# Create another column vector
b = np.array([10,20,30,40,50]).reshape(-1,1)
print('b = ', b)
print('Shape of numpy array b is ', b.shape)

# Do inner product
c = np.dot(a.T, b)
print('c = a.T*b =', c)
print('Shape of inner product c is', c.shape)

# Do outer product
d = np.outer(a,b) # Or equivalently np.dot(a, b.T) would still give the same result
print('d = a*b.T =', d)
print('Shape of outer product d is', d.shape)

# Inferring inner product out of outer product
# Inner product = sum(trace(outerproduct(a,b)))
f = np.sum(np.trace(np.outer(a,b)))
print('f = sum(trace(outerproduct(a,b))) is', f)

a =  [[1]
 [2]
 [3]
 [4]
 [5]]
Shape of numpy array a is  (5, 1)
b =  [[10]
 [20]
 [30]
 [40]
 [50]]
Shape of numpy array b is  (5, 1)
c = a.T*b = [[550]]
Shape of inner product c is (1, 1)
d = a*b.T = [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]
 [ 50 100 150 200 250]]
Shape of outer product d is (5, 5)
f = sum(trace(outerproduct(a,b))) is 550


## Convert back and forth between numpy array and list

In [34]:
# Convert list to numpy array
a = [1,2,3,4,5]
print('List a = ', a)
b = np.array(a)
print('Numpy array of list a is b =', b)

# Convert numpy array to list
c = b.tolist() # here b is a numpy array constructed as above
print('The list corresponding to numpy array b is c =', c)

List a =  [1, 2, 3, 4, 5]
Numpy array of list a is b = [1 2 3 4 5]
The list corresponding to numpy array b is c = [1, 2, 3, 4, 5]


## Analyze matrices as n-d numpy arrays

In [42]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print('Matrix A Defined Using Numpy Array is', A)
print('Size of matrix A is', A.shape, 'That is:', A.shape[0],'rows and', A.shape[1], 'columns')

Matrix A Defined Using Numpy Array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Size of matrix A is (3, 3) That is: 3 rows and 3 columns


## Create Matrix of ones and zeros or required size

In [56]:
# Specify Matrix Size
m = 3
n = 4
# Matrix of ones with m rows and n columns
A = np.ones((m,n))
# Matrix of zeros with m rows and n columns
B = np.zeros((m,n))
print('A = ', A)
print('Shape of A is', A.shape)
print('B = ', B)
print('Shape of B is', B.shape)

# Create transpose of matrix
C = A.T # or np.transpose(A) or A.transpose() will give the same answer
print('Transpose of matrix A will be of shape', C.shape, 'and is given by', C)

A =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape of A is (3, 4)
B =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of B is (3, 4)
Transpose of matrix A will be of shape (4, 3) and is given by [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Multiply two matrices
Both A @ B and np.dot(A, B) will do the same job

In [51]:
A = np.random.rand(3,3)
B = np.random.rand(3,4)
C = A @ B
D = np.dot(A,B) 
print('A*B =', C)
print('A*B =', D)

A*B = [[0.33976145 0.27559023 0.26318764 0.25707438]
 [0.31638135 0.29658541 0.24483385 0.2450245 ]
 [1.11846119 0.71297346 0.81610689 0.92495537]]
A*B = [[0.33976145 0.27559023 0.26318764 0.25707438]
 [0.31638135 0.29658541 0.24483385 0.2450245 ]
 [1.11846119 0.71297346 0.81610689 0.92495537]]


## Element wise multiplication of two matrices - Hadamard product of two matrices

In [58]:
A = np.array([[1,2],[3,4]])
B = 5*np.ones((2,2))
C = np.multiply(A,B)
print('Hadamard product of A,B is', C)

Hadamard product of A,B is [[ 5. 10.]
 [15. 20.]]


## Get Rank of Matrix

In [50]:
A = np.random.rand(3,3)
print('A = ', A)
rank_A = np.linalg.matrix_rank(A)
print('Rank of Matrix A is', rank_A)

A =  [[0.71235426 0.70333479 0.7605381 ]
 [0.88975069 0.7361289  0.1064568 ]
 [0.86966123 0.97953876 0.81880405]]
Rank of Matrix A is 3
